### ISSUE TITLE
Switch to next is captured by "Microsoft Teams Audio"

### ISSUE THREAD

**Issue by JKuhn** [deweller/switchaudio-osx#42]
After installing Microsoft Teams, `SwitchAudioSource -n` always only switches to "Microsoft Teams Audio".
Other audio sources are available and printed with `SwitchAudioSource -a`.

**Comment by derjogi** [comment]
In case anyone else is running into this, I've added an exclusion for MS Teams, the `-n`ext cycling works again 🤩
(I had to zip it so I can upload it to GitHub, you can see the changes I've made in the forked repo. I'm not sure whether it should be merged because it is quite specific and probably not the best fix, I'm not a C dev 😅 )
[AudioSwitcherIgnoreTeams.zip](https://github.com/deweller/switchaudio-osx/files/10515815/AudioSwitcherIgnoreTeams.zip)

**Comment by deweller** [comment]
Glad you came up with a solution for this.
